### PR TITLE
Refactor app v1.2

### PR DESCRIPTION
**Pull request by Graeme-Smith**
New repo created for dna nexus app components of the Coverage_Uniformity_Report tool, the docker compoenents remain in the original repo - Coverage_Uniformity_Report

Added additional user provided options for:

- User can specify that they want the results from some Pan numbers grouped together, for example if several Pan numbers on a run use the same capture kit.
- User can select which plots to show (Useful for large data sets which may be very slow to process).
- User can now specify the input folder if sambmaba output is not found in the default location.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[README.md, line 22 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6Bwi71XCjY9xbplzv:-Mk6Bwi71XCjY9xbplzw:b-cgu5xc) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/README.md#L22)):*
> ```Markdown
> 
> ## How does this app work?
> At the core of the app is a dockerised R script (See mokaguys/Coverage_Uniformity_Report repo) which reads in all data from the folder coverage/raw_output/ in the project, cleans up the data, and outputs html, pdf, and csv reports.
> ```

no biggy but the underscores are causing italics
___
*[sambamba_coverage_uniformity_dxapp/dxapp.json, line 71 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6D5xbCrLYkDZ5f1LT:-Mk6D5xbCrLYkDZ5f1LU:b-b6uk3l) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/sambamba_coverage_uniformity_dxapp/dxapp.json#L71)):*
> ```JSON
>     "file": "src/code.sh",
>     "release": "20.04",
>     "version": "0",
> ```

Can you check the folder /repo structure. the json, readme, src and resource folders are usually in the top level of the directory
___
*[sambamba_coverage_uniformity_dxapp/README.md, line 33 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6CO6K5dLeV43zo7oS:-Mk6CO6K5dLeV43zo7oT:b-jckr08) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/sambamba_coverage_uniformity_dxapp/README.md#L33)):*
> ```Markdown
> ## What are the limitations of this app?
> 
> Large data sets containing many regions/samples may require turning off the interactive plots due to performance issues. 
> ```

duplicate file? can you check which one is most up to date and put it at /README.MD

**Comment by Graeme-Smith** [comment]
___
*[README.md, line 22 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6Bwi71XCjY9xbplzv:-MlnW7L5A-gFcZI9kBSX:b-1lh26t) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/README.md#L22)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

no biggy but the underscores are causing italics
</blockquote></details>

I've escaped the underscores

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[sambamba_coverage_uniformity_dxapp/dxapp.json, line 71 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6D5xbCrLYkDZ5f1LT:-MlnZ1xQ7x-grhd-PACD:b-q6d2op) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/sambamba_coverage_uniformity_dxapp/dxapp.json#L71)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can you check the folder /repo structure. the json, readme, src and resource folders are usually in the top level of the directory
</blockquote></details>

Refactored App
___
*[sambamba_coverage_uniformity_dxapp/README.md, line 33 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-Mk6CO6K5dLeV43zo7oS:-MlnYvu17lShHQtYFLQE:ba3dfob) ([raw file](https://github.com/moka-guys/dnanexus_coverage_uniformity_report/blob/1f2f57c2875cb49f52c39704eb145b5160d49bca/sambamba_coverage_uniformity_dxapp/README.md#L33)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

duplicate file? can you check which one is most up to date and put it at /README.MD
</blockquote></details>

Removed

**Review by aledj2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_coverage_uniformity_report/1#-:-MmxTTUe2AFxEa9YlUlZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
